version: '3'
services:
  connector-cluster25:
    image: luigidituccio/opencti-connector-cluster25:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=ChangeMe
      - CONNECTOR_SCOPE=report # MIME type or Stix Object
      - CONNECTOR_CONFIDENCE_LEVEL=100 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - CLUSTER25_INTERVAL_SEC=120
    restart: always
